### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by keeano92**
Migrating up the new changes and reflection to DEX.

### CODE REVIEW

**Review by camdengrieh — DISMISSED** [review]

**Comment by camdengrieh** [comment]
> This pull request is automatically being deployed by Amplify Hosting ([learn more](https://aws.amazon.com/amplify/hosting/)).
> 
> Access this pull request here: https://pr-103.d2gq3kp4amkvkr.amplifyapp.com

Anyone having issues with getting the dApp to load?

**Comment by keeano92** [comment]
@camdengrieh Seeing an error in the console. nice catch. Wasnt doing that on my first check or local.

**Comment by GhostWalker562** [comment]
I got it too, it's in token-price.ts because there's no provider I'm assuming

**Comment by camdengrieh** [comment]
Okay should be working now, JSON provider added and the MEMO address...

**Pull request merged**
