### PR TITLE
Redemption / GTFO

### PR DESCRIPTION
**Pull request by mtpUAE**
## Description
Add Redemption Page
Add Styling for Redemption Page
Add the Smart Contract into to the config
Create a thunk that checks the RUG token has allowance on aforementioned smart contract, allows you to approve if not, and allows you to stake if true

## How To Review This

- Add a small amount of USDC.e into smart contract.
- Acquire RUG token
- Approve contract on UI - Redeem page
- Refresh the dApp
- Then swap the acquired RUG - Ensure the amount of USDC received from the swap reflects the applied RFV * amount of RUG

## Checklist:
- [x] I have run yarn lint and there are no lint or typescript errors.
- [x] The production build passes.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed locally.

### CODE REVIEW

**Comment by keeano92** [comment]
@Crohmies There is a build error not allowing it to build properly.
Please see the error here:
`2022-03-25T20:38:58.917Z [INFO]: yarn install v1.22.0
2022-03-25T20:38:59.002Z [WARNING]: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
2022-03-25T20:38:59.005Z [INFO]: [1/4] Resolving packages...
2022-03-25T20:38:59.173Z [WARNING]: error Can't add "ethereumjs-abi": invalid package version undefined.
2022-03-25T20:38:59.173Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2022-03-25T20:38:59.196Z [ERROR]: !!! Build failed
2022-03-25T20:38:59.198Z [ERROR]: !!! Non-Zero Exit Code detected
2022-03-25T20:38:59.198Z [INFO]: # Starting environment caching...
2022-03-25T20:38:59.198Z [INFO]: # Environment caching completed
Terminating logging...`

This can probably be fixed easily by locating the conflict with the above package and yarn. Let me know if you need the full log dump.

**Comment by keeano92** [comment]
@Crohmies We also do not allow merges into master directly. This has to be merged into our staging branch for the PR.
once you address the above error please re-create this PR from your feature branch and our staging branch. Then our CI/CD process handles everything automatically once reviewed by me. :)

**Comment by mtpUAE** [comment]
Okay. I added no additional packages to the project, I just ran npm install to install the node_modules listed in the package-lock.json, so i'm not sure thats a problem my end, maybe there is new package version published on npm and not yarn??

I will commit my PR to staging in future...
Thanks,

**Comment by keeano92** [comment]
I see what happened. 
Please delete the package lock file for NPM and it will build.

@mtpUAE 

On the next PR if thats done it should build and allow us to see the amplify preview

**Pull request closed without merging**
