### PR TITLE
wsRug Support

### LINKED ISSUE #96: [Feature] Wrapped Rug
### Summary
For those who want to avoid taxes, they should be able to wrap up their rug into wRUG. It's really easy to do, just fork the wMEMO smart contract and change the address. Basically wMEMO receives the rebases instead of a person and then when they unwrap and the contract will give them the MEMO accordingly, pretty straightforward tbh.

### Solution
File attached (It's a txt because github doesn't allow sol :/)
[wsRug.txt](https://github.com/RuGenerous/rugenerous-frontend/files/7655453/wsRug.txt)

### How to deploy
Just put the sRUG contract address and deploy

### PR DESCRIPTION
**Pull request by GhostWalker562**
## Summary
Frontend support for wrapped rug. Forked from Wonderland.

Deployed verified wsRug contract
https://snowtrace.io/address/0x8d6722a6d95b053a62a038bd72c191ca96076a6a#code

Should close #96

### CODE REVIEW

**Review by camdengrieh — CHANGES_REQUESTED** [review]
Typo’s ‘unwraping’ needs changing to ‘unwrapping’...

**Comment by camdengrieh** [comment]
Thanks again for your contribution @GhostWalker562.
I will however have to ask @DreesusChrist to deploy the wsRUG contract and that we use the address deployed from him...
We will take the source code from snowtrace 🤝

**Comment by GhostWalker562** [comment]
> Thanks again for your contribution @GhostWalker562. I will however have to ask @DreesusChrist to deploy the wsRUG contract and that we use the address deployed from him... We will take the source code from snowtrace 🤝

I'll make those changes. Yeah don't use the contract I got, just deployed it for an example, the only thing is that when I call on the smart contract I use wording relative to RUG instead of MEMO so that's one that I'd like to point out. If you end up using wMEMO ping me again and I can make the changes accordingly, otherwise, the contract code is on #96 or snowtrace for reference.

**Comment by GhostWalker562** [comment]
@camdengrieh Done. Thanks for your contributions too, you work so hard man. I'm just trying to get some experience working in React so that's why I decided to help. Hopefully the experience here will help me get into a college in future 😅 cause any experience is good experience ig

**Comment by timothyjlaurent** [comment]
I would be nice to _somehow_ show the wrapping interface on mobile devices.

**Comment by keeano92** [comment]
> I would be nice to _somehow_ show the wrapping interface on mobile devices.

That is a really good request, I have been a mobile-first dev for over 15 years and think we should allow this as well. 
I will work on it and add it into our list, I think this will address a couple issues we will see on mobile too

**Comment by GhostWalker562** [comment]
Gotcha @keeano92 @timothyjlaurent, do you want support for that in this pr or later? Because the issue is that I don't know where to put it. We can't really have hamburger, well we can but it'll be weird because we'll have a hamburger and a drawer.

**Comment by keeano92** [comment]
> Gotcha @keeano92 @timothyjlaurent, do you want support for that in this pr or later? Because the issue is that I don't know where to put it. We can't really have hamburger, well we can but it'll be weird because we'll have a hamburger and a drawer.

That feature is added to the project board and dont have to worry about it being in this PR. We can save that for a later one. :)

**Comment by johncastorina** [comment]
is this feature still in the works, or becoming stale?

**Comment by GhostWalker562** [comment]
> is this feature still in the works, or becoming stale?

It's been go to go for a bit, just waiting on deployment and for one of the devs to take a look at it again

**Pull request closed without merging**
