### PR TITLE
Add buy screen for RUGDUX and TraderJoe

### PR DESCRIPTION
**Pull request by 1avantgarde**
Added View with embedded iFrame for RugDex and TraderJoe access

### CODE REVIEW

**Comment by keeano92** [comment]
@1avantgarde I love this it looks great, I feel some things just need to be adjusted on the front end to quantify this update. Like the button in the upper right-hand side that says RUG and then list these two DEXs you cover in this module. 
@camdengrieh Again I love this and really think we should include it. Do you think we should take the top menu and add a new button titled "Tokens" and then turn the "RUG" button into "BUY RUG" and link it to this feature, then we would just remove the left-hand nav to keep it simplified so it's not too hard for individuals to see the documentation?

**Review by GhostWalker562 — COMMENTED** [review]
deleted the review in favor for keeano

**Comment by keeano92** [comment]
@GhostWalker562 I see this is set to go into master again lol Can you adjust that, to be staging. I know it selects it auto and can be a pain for me as well.

**Comment by GhostWalker562** [comment]
@1avantgarde ^ think he meant to ping you

**Pull request closed without merging**
